# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shedmat1 <- function(a, p) {
    .Call('_APO_shedmat1', PACKAGE = 'APO', a, p)
}

APO2 <- function(X, lambda, p, c, beta) {
    .Call('_APO_APO2', PACKAGE = 'APO', X, lambda, p, c, beta)
}

